### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by inrussiawithhate** [brunnopleffken/addictive-community#10]
Problem install: Checking information and connecting to database... FAILED

how to fix it?

**Comment by brunnopleffken** [comment]
Hello @inrussiawithhate 
This error happens in Step 2. It just reads the configuration file (config.php) and tries to connect to database. Make sure you have entered your MySQL information correctly (hostname or IP address, username and password).

I'll improve the installer to check DB information as soon as you type these info.

**Comment by inrussiawithhate** [comment]
The system does not work on free hosting, although write the correct data to MySQL. I bought a paid hosting - the system works!
