### ISSUE TITLE
so many errors

### ISSUE THREAD

**Issue by inrussiawithhate** [brunnopleffken/addictive-community#103]
Hello!
The system has so many bugs (or at least I found ones)
Each link that has no id parameter displays the error. This concerns and root directory. That will check controllers. For example open site.com/22 - op mistake again.

site.com/room/ - mistake again.
site.com/room/last_post/22 - mistake again.

![error1](https://cloud.githubusercontent.com/assets/7196689/16900591/ef82cb12-4c30-11e6-9abb-bd05af1ef5f5.jpg)

![error2](https://cloud.githubusercontent.com/assets/7196689/16900593/f7ba120e-4c30-11e6-8fb9-df5d99cc0fc8.jpg)

![error3](https://cloud.githubusercontent.com/assets/7196689/16900598/2f52f33e-4c31-11e6-8434-1812d3914583.jpg)

![error4](https://cloud.githubusercontent.com/assets/7196689/16900600/34249458-4c31-11e6-8fcb-4902d267b49b.jpg)

**Comment by brunnopleffken** [comment]
OK, let's do it by steps:

1 - Some of them aren't bugs, by the _literal_ mean of the word. You're hard typing random URLs and the controllers aren't treating null IDs nor null values as they are supposed to be passed as parameter. TO DO: What I can do in case of a non-existing ID is to redirect the user back to home.

2 - Your Apache server seems to be configured as 'display_errors = on', which isn't supposed to be in production environment. In a regular server environment and in case of error the user will come across a blank screen.

3 - About the controller errors, once again you're hard typing URLs and replacing controller names with non-existing ones, but I can improve the way the router's RegEx deals with URLs so it can be more error-proof (a.k.a. redirect the user back to home in case of a non-existing controller name).

**Comment by brunnopleffken** [comment]
Closed as now we have better XSS support and custom 404/500 pages in case of server-side or mistyped URLs.
