### ISSUE TITLE
Update Software version to v0.11.0

### ISSUE THREAD

**Issue by halojoy** [brunnopleffken/addictive-community#105]
When I run 0.11.0 in admin CP it says Software is v0.10.0
and that I can update to v0.11.0.

I think you have forgot to update some data to the new version.
There should be one data v0.11.0 in init.php
and one such data in installer.php

**Comment by brunnopleffken** [comment]
Yeah, indeed. I forgot to change the version in these files. So... released as 0.11.1!
Thanks, as always! ;)
