### ISSUE TITLE
bug with Cyrillic

### ISSUE THREAD

**Issue by inrussiawithhate** [brunnopleffken/addictive-community#121]
When I try to let my topic Cyrillic displays this error:

Fatal error: Class 'Transliterator' not found in C:\xampp\htdocs\kernel\Text.php on line 172

**Comment by brunnopleffken** [comment]
Which PHP version are you using? Since version 0.12, Addictive Community uses the embedded Transliterator from PHP 5.4 to translate cyrillic, greek, etc. characters to latin.

More info: http://php.net/manual/pt_BR/transliterator.transliterate.php

**Comment by brunnopleffken** [comment]
@inrussiawithhate 
I sent a commit changing this. Can you perform some tests?
It's not released yet, you must use the _'development'_ branch.
Thanks!

**Comment by zalexstudios** [comment]
To inrussiawithhate!
Use Russian localhost script Denwer!
And will be all ok!!!
Если ты Русский пиши по Русски я отвечу.

**Comment by brunnopleffken** [comment]
Fixed in v0.12.1
