### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by inrussiawithhate** [brunnopleffken/addictive-community#16]
I have a problem with the installation! Try to install the system VPS but steady returns Error!

Unable to connect to MySQL server.

What caused this? On the same server is installed MyBB forum, which work correctly.

**Comment by brunnopleffken** [comment]
Hello @inrussiawithhate . Thanks for your report, I'm investigating this issue and release this fix as critical. I'll do some tests here but I need further information...

Is the MySQL server installed on the same server as your HTTP server?
Did you try to connect using IP address or an alias? Or both?

This first step verification is just a basic one, trying to connect to your MySQL server using `mysqli_connect` and Ajax using your hostname, username and password (relative to the HTTP server)...

If you're willing to do some tests, try to create a PHP script with the following code:

```php
mysqli_connect($hostname, $username, $password);
echo mysqli_connect_error();
```
Let's see if it shows any error message... ;)

**Comment by brunnopleffken** [comment]
@inrussiawithhate 
I downloaded the v0.1.0 and did some tests, and everything works fine! Using IP addresses and alias, seems to be OK. Aside the script I posted above, try to add the port number to your hostname (most common is port 3306, but might be any other number)...
If you're still unable to proceed, please, let me know!
