### ISSUE TITLE
installation problem #2

### ISSUE THREAD

**Issue by inrussiawithhate** [brunnopleffken/addictive-community#26]
Hello, installation problem # 2....

Error!

Access denied for user 'www-data'@'localhost' (using password: NO)

Addictive Community - (c) 2015 All rights reserved.

**Comment by inrussiawithhate** [comment]
And bugs with report:

Error!

An error occoured on the following query: INSERT INTO c_reports (description, reason, date, sender_id, ip_address, post_id, thread_id, referer) VALUES ('43', '1', '1434837871', '1', '::1', '6', '3', 'http://localhost/thread/3');
Addictive Community - (c) 2015 All rights reserved.

**Comment by brunnopleffken** [comment]
Thanks @inrussiawithhate I just fixed the second error (post/thread report) and it'll be released and credited to you in the next release! ;)

About the first issue (installation problem), it's more like an error when authenticating to your database... Seems like you're not using password, it's right? Try to connect to 127.0.0.1, or manually insert the port number (usually 3306).
