### ISSUE TITLE
Add Reply INSERT INTO Error

### ISSUE THREAD

**Issue by halojoy** [brunnopleffken/addictive-community#30]
I can create a New Thread with a post to go with it. It works perfectly.
But when I try to Add Reply there is an Error:

"An error occoured on the following query: INSERT INTO c_posts (author_id, thread_id, post_date, ip_address, post, quote_post_id, best_answer, first_post, attach_id) VALUES ('1', '2', '1435050390', '188.122.128.27', 'test for a new post', '', '0', '0', '0');"

**Comment by halojoy** [comment]
I found the error.
"quote_post_id" => Http::Request('quote_post_id'),
Works not. Expecting a numeric value. Error for empty string= ''

"quote_post_id" => 0,
Works!

**Comment by brunnopleffken** [comment]
Http::Request() returns false when no value is found (and 'quote_post_id' allows NULL).
I'll do a conditional to always set this to zero if not quoting another reply.

Thanks! ;)
