### ISSUE TITLE
Creating new Room database error

### ISSUE THREAD

**Issue by halojoy** [brunnopleffken/addictive-community#31]
I got database error when trying to create a new room.
'rooms' table has one item 'threads'
When I changed this item in database to accept NULL, everything is okay.

**Comment by brunnopleffken** [comment]
Ops, my bad! This is a NOT NULL field, so it should be saving zero instead of NULL (because a new room contains zero threads and it is incremented each new thread)...

I'll fix this! Thank you one more time! ;)
