### ISSUE TITLE
DB Error when update member profile.

### ISSUE THREAD

**Issue by halojoy** [brunnopleffken/addictive-community#33]
I get the following:
An error occoured on the following query: UPDATE c_members SET email = 'my_email_here', hide_email = '1', member_title = '', location = '', profile = '', b_day = '', b_month = '', b_year = '', gender = 'M', website = '', im_facebook = '', im_twitter = '' WHERE m_id = 2;

This one I don't understand. Most fields should accept a NULL ....

edit: When I submit birthday data it is ok.

**Comment by brunnopleffken** [comment]
But those fields (b_day, b_month and b_year) allow NULL values, as seen below:

```sql
  [...]
  `b_day` int(2) DEFAULT NULL,
  `b_month` int(2) DEFAULT NULL,
  `b_year` int(4) DEFAULT NULL,
  [...]
```
Running this SQL directly on DB, works fine:

![screen-shot-2015-06-23-at-2 24 57-pm](https://cloud.githubusercontent.com/assets/3427344/8313279/210e73c2-19b8-11e5-8174-06d2903ea45f.png)
