### ISSUE TITLE
SQL Injections. & file Attachments accept .PHP file

### ISSUE THREAD

**Issue by logames** [brunnopleffken/addictive-community#39]
hello, please fix its.
usercp/photo?m=1
how to inject usercp/photo?m=1'
ERROR:  Notice: Undefined index: 1' in C:\xampp\htdocs\project\controllers\Usercp.php on line 170

attachments accept php file with tamper data addons mozilla firefox.
.php.jpg edit to .php
and shell on public/attachments/3/1436027285/local.php

thanksyou
sorry bad english

**Comment by brunnopleffken** [comment]
Hello @logames 
Thank you for your report. I'll check not just User CP controller, but all other controllers, looking for these kind of security breaches (including rewrite some methods). They will be fixed and released as maximum priority!

**Comment by brunnopleffken** [comment]
Oh, and by the way, the apostrophe you saw on the error message is an ```&apos;```, not an actual apostrphe/single quote (see the source-code, you'll see ```Notice: Undefined index: 1&apos; in [...]```... So, the SQL is safe, but anyway I'm sanitizing numeric-only input fields...

**Comment by brunnopleffken** [comment]
Fixed! All numeric-only fields (like IDs) are passing through validation. And all strings are sanitized to HTML entities, so, there's no actual symbols like semicolon or apostrophe that could allow SQL injection.

Thank you one more time! ;)
