### ISSUE TITLE
Failed to open stream error in teamplates

### ISSUE THREAD

**Issue by Tehiro** [brunnopleffken/addictive-community#4]
When I go to Teamplate Manager, Email, etc. I get the error in attach.
![2015-01-19 07_54_49-addictive community - administration panel](https://cloud.githubusercontent.com/assets/4751246/5796898/b8d13c26-9fb0-11e4-820a-9537e103e68a.png)

**Comment by brunnopleffken** [comment]
Hello @Tehiro, the "Templates" section in Admin CP is still currently under development... Here in my build I already have the "Template Manager" subsection. Nice touch, I'll get this thing done soon as possible!

I'll keep this issue open until this section is committed to master.

Thanks!!

**Comment by Tehiro** [comment]
Good. I can't help you with this. I have to wait :)
