### ISSUE TITLE
Tried the 0.6.0 install. Get error. Missing 'default'.

### ISSUE THREAD

**Issue by halojoy** [brunnopleffken/addictive-community#40]
When I click Let's Go in step 5 of install I get this from index.php:

ERROR! Language files or keywords are missing for .

Notice: Undefined variable: url in C:\Apache24\htdocs\addictive-0.6.0\kernel\Core.php on line 117

Notice: Undefined index: m_id in C:\Apache24\htdocs\addictive-0.6.0\controllers\Application.php on line 139

Notice: Undefined index: m_id in C:\Apache24\htdocs\addictive-0.6.0\controllers\Application.php on line 143

Notice: Undefined index: usergroup in C:\Apache24\htdocs\addictive-0.6.0\controllers\Application.php on line 108

Notice: Undefined index: usergroup in C:\Apache24\htdocs\addictive-0.6.0\controllers\Community.php on line 79

Warning: require(templates//Community.Main.phtml): failed to open stream: No such file or directory in C:\Apache24\htdocs\addictive-0.6.0\index.php on line 178

Fatal error: require(): Failed opening required 'templates//Community.Main.phtml' (include_path='.') in C:\Apache24\htdocs\addictive-0.6.0\index.php on line 178

There is a 'default' missing in 'templates/default/Community.Main'.
I have looked in the database tables. 'default' is there. So it is some script error.

**Comment by brunnopleffken** [comment]
Wow, that's weird. I never got this issue before and I'm unable to reproduce it.
Take a look at ```c_config```, looking for a field named ```theme_default_set```. Is it there?

In **index.php** this is defined on the line 202 and saved on ```$this->template```. Right after the "else", add the following line:

```php
String::PR($this->template);
```

Does it return any value?

**Comment by brunnopleffken** [comment]
Hey @halojoy 
Any good news? Is everything working properly?
If not, let me know!

**Comment by halojoy** [comment]
I tried the String::PR($this->template); But it does not show anything.
template_default_set is 'default'

It is very strange I get these issues. One thing, I run the MySQL is strict mode. But this should not be a prooblem.

I have been away for 10 days.

I suspect I have a problem. I say probably your code is good.
Because I have done install of MyBB and UseBB
and  I get some error from them. Error in the initial defines.
But what can it be?

**Comment by brunnopleffken** [comment]
Hmm, I'll see if I run MySQL in strict mode I get this issues. And also you're getting all these "undefined variables/index" notices when calling for user groups, member IDs, etc. All these settings are defined in `Main()` (index.php), that's why I said you to see what's inside `$this->template`...

How is your MySQL log?


NOTE: `String::PR()` is the same as `print_r()`, but wrapped with `<pre>` tags... ;)

**Comment by halojoy** [comment]
this line is executed:
$this->template = $this->Session->member_info['template'];
But the value after this is NULL.

I also var_dump $this->Config. It looks to be very good. Values has been received from DB.

**Comment by halojoy** [comment]
Solved!
I deleted first all sessions. Not any better.
I deleted all cookies in Firefox. Much better. No notices and no errors.

Can be a leftover COOKIE from previous install.
I dont think Addictive creates cookies while installation?

**Comment by brunnopleffken** [comment]
The Session class checks if cookies are defined, but not if cookies are empty. Of course, an empty cookie will return... empty...

As I'm unable to reproduce this, I'll just do a second step to check if the cookie *member_id* is >= 1 (if not Addictive Community will treat the member as a guest) and hope that it works out.
