### ISSUE TITLE
problem with login

### ISSUE THREAD

**Issue by inrussiawithhate** [brunnopleffken/addictive-community#41]
Hello!

Error!

Variable 'remember' must be a number.

**Comment by brunnopleffken** [comment]
This happens when you uncheck "Remember my current session"?
I'm unable to reproduce, but I'll try to get this error.

**Comment by brunnopleffken** [comment]
I found it... `remember` and `anonymous` doesn't pass any values.
When logging in, we just check the existence of these variables, not the values.

Fixed!
Thanks!!
