### ISSUE TITLE
Edit post does not work.

### ISSUE THREAD

**Issue by halojoy** [brunnopleffken/addictive-community#43]
I try to edit post I submitted.
When I have changed post and push button 'Edit'
I get this:
"You cannot edit a post that you did not publish."

Deleting post works, but not edit.

**Comment by brunnopleffken** [comment]
Hmm... You're trying to edit other member's post as Administrator?
I'll check this out.

**Comment by halojoy** [comment]
No. I have posted this myself as Admin.
But can not edit. Delete works.

**Comment by halojoy** [comment]
Now I can edit my post.
I thnik you have solved this.
I close this.

**Comment by halojoy** [comment]
As an admin I can edit posts. It works now.
But not the first Welcome post. There is no edit button for first post.

As a normal member I can not edit my post.
When submit from editor I get: "You cannot edit a post that you did not publish."
Delete of posts is working.

**Comment by brunnopleffken** [comment]
I'll get a time to rewrite these permissions, perhaps extract it to a method, otherwise I might get stuck in these fixes of already fixed code...

I will work on it! ;)

**Comment by brunnopleffken** [comment]
Well, I think I got it!
`$this->Session->session_info` returns information about the currently logged in member. OK. But `Http::Request()` also get cookies (as cookies are also $_REQUEST). These values were conflicting.

Can you please test this fix to see it it solves this issue?

**Comment by halojoy** [comment]
Now It works!
I think you have fixed it.

**Comment by brunnopleffken** [comment]
Edit first post is here! ;)

**Comment by halojoy** [comment]
Nice. A button EDIT for first post.
Unfortunately I get a SQL error when pushing the button:
An error occoured on the following query: SELECT title FROM c_threads WHERE t_id = ;

**Comment by brunnopleffken** [comment]
Oh man, bad bad mistake.
I was passing thread ID as parameter instead of post ID.
My bad! =P

I think it's working now!

**Comment by halojoy** [comment]
It works now.
You are very good. But it is naturally. You know your forum software well.

**Comment by brunnopleffken** [comment]
Thanks!! This is one of the advantages of building its own framework...

Well, I think this issue is closed then!
I'm really thankful for your support!
