### ISSUE TITLE
New Thread error

### ISSUE THREAD

**Issue by halojoy** [brunnopleffken/addictive-community#45]
Create new thread works for Admin.
But when I try to create New Thread as normal member I get this database error:

An error occoured on the following query: INSERT INTO c_threads (title, slug, author_member_id, replies, views, start_date, room_id, announcement, lastpost_date, lastpost_member_id, locked, approved, with_bestanswer, poll_question, poll_data, poll_allow_multiple) VALUES ('Third Thread', 'third-thread', '2', '1', '0', '1437300554', '1', '', '1437300554', '2', '', '1', '0', '', '', '0');

But no problem posting Reply.

**Comment by brunnopleffken** [comment]
I just copied and pasted in MySQL console and everything works fine (no SQL errors). These SQL error messages are too ambiguous, I'll send a commit changing this error message to make it more clear and then you try again.

This may help us to identify what's going on...

**Comment by halojoy** [comment]
I think my  MySQL does not work as yours. I am quite sure it is same as we had before. When having non numeric value in a numeric field.

**Comment by brunnopleffken** [comment]
OK. Now I enabled strict mode on my MySQL server.
And you're right: incorrect integer value.

I think it's now fixed!
