### ISSUE TITLE
Nice to see Manage Members, but one question

### ISSUE THREAD

**Issue by halojoy** [brunnopleffken/addictive-community#51]
Nice to see you have started with Manage Members.
After all manage forum posts and manage users is the most important in a forum.
So, maybe after next release you can put up a version of Addictive-community
as a support forum, where people can ask questions and post.

Now my question. I see you have very well made a form for Editing member.
But maybe you forgot to add User Group.
I think it should be there with a drop-down menu to change usergroup.

**Comment by brunnopleffken** [comment]
About the member management part, I'm still working on a way to not return errors when reading a thread that contains a post of a deleted member.

User group. Yeah, I forgot that.
I'll fix this with a drop-down soon!

**Comment by halojoy** [comment]
Maybe add a dummy instead of deleted member.
Called 'deleted member' or something.
So, instead of deleting the id, you put in something else at that user id.

**Comment by halojoy** [comment]
I updated my software. Now when I press Delete button, SQL is not performing a DELETE. It performs an  UPDATE. Changing the username, usertype and delete the password.
Like this:
if(isset($_POST['del_id'])){
	$dbh->exec( "UPDATE users SET usertype = 'deleted', username = 'Deleted', passhash = '' WHERE id = ".$_POST['del_id'] );
}

**Comment by brunnopleffken** [comment]
Nice! It doesn't actually delete the member, it just quite "disables" it, emptying all other fields.
Sounds nice! I'll implement this way, sounds easier and better to maintain.

**Comment by halojoy** [comment]
It works for me in my forum.
But I had to change store in my databasefields.
I had the username in several tables.
Now I have only the username in 'users' table.
At the other places only refering to the id-number.

**Comment by brunnopleffken** [comment]
That's it! User group is set to zero for deleted members. Usernames are shown in dark red, members profiles are disabled and if someone try to see it, an error message will be fired ("Profile doesn't exist").

Seems nice:

<img width="956" alt="screen shot 2015-07-28 at 11 00 17 pm" src="https://cloud.githubusercontent.com/assets/3427344/8948339/84c64e14-357c-11e5-9c18-b710df0d4c84.png">

**Comment by halojoy** [comment]
Good Work.
The alternative had been less good.
