### ISSUE TITLE
Facebook photo

### ISSUE THREAD

**Issue by halojoy** [brunnopleffken/addictive-community#55]
I added my facebook link and selected facebook photo.
But it does not work.

This is the error from facebook:
{
   "error": {
      "message": "(#803) Cannot query users by their username (hal.ojoy.3)",
      "type": "OAuthException",
      "code": 803
   }
}

**Comment by brunnopleffken** [comment]
Yeah, this made me nuts!! In late June, Facebook deprecated their support for Graph API v1 (that allowed direct access to basic information: name, photo, etc.), so now I need to use Graph API v2 or higher, that requires authentication. So, I need to create an authentication method to link Facebook accounts to Addictive Community accounts using their newer API.

**Comment by halojoy** [comment]
Gravatar should work. But I have not tested it.

**Comment by brunnopleffken** [comment]
Gravatar is working fine! The e-mail address you set in Addictive Community should be the same registered in Gravatar, and then the magic happens...
