### ISSUE TITLE
disable mod rewrite and add emoticons

### ISSUE THREAD

**Issue by inrussiawithhate** [brunnopleffken/addictive-community#57]
Hello! How do stop mod_rewrite in rooms and how i add emoticons?

**Comment by brunnopleffken** [comment]
For now, there's no way to disable Apache's mod_rewrite. I can consider you suggestion and add it to backlog, but will require some time of work.

You can manage emoticons accessing:
Admin CP > Themes & Templates > Emoticons

"Add New Emoticons" is a new feature already built in v0.9.0, but this version is quite frozen. Another new feature in 0.9.0 is flood control. After two months still, I want to resume work on it soon and release new updates.


*To add emoticons you need to do it manually, adding and removing register in c_emoticons table in DB. I don't recommend you to do it, an specific Admin CP panel will be here to automate it, but you can try.*
