### ISSUE TITLE
Obsolete threads

### ISSUE THREAD

**Issue by halojoy** [brunnopleffken/addictive-community#62]
In Admin CP is a setting to enable Obsolete threads.
I have NOT ticked that option.
Still threads more than 60 days old become obsolete.
They should not be obsolete.

**Comment by brunnopleffken** [comment]
Yeah, this shouldn't happen. I'll check this out!
Thanks for reporting! ;)

**Comment by halojoy** [comment]
Now it works perfect.
Well done!
