### ISSUE TITLE
Update Addictive Community to be PHP7 compatible

### ISSUE THREAD

**Issue by brunnopleffken** [brunnopleffken/addictive-community#63]
While Addictive Community is totally compatible with PHP 5.3 or higher, it's broken in PHP7. Our goal is to make Addictive Community work in PHP7 smoother than ever.

But remember: to make it still compatible with the popular PHP 5.3+ we'll **not** implement the new PHP7 features, like type declarations or the new operators.

**Comment by halojoy** [comment]
Good idea. PHP7 is still not mature. But it is good to make AC compatible.

**Comment by brunnopleffken** [comment]
Indeed, @halojoy!
Actually there's not too much to change, but small things can break the entire code. I need to do further tests, but I think everything is working properly on PHP7 now!
