### ISSUE TITLE
Server info in Community Dashboard

### ISSUE THREAD

**Issue by halojoy** [brunnopleffken/addictive-community#66]
There is a value $_SERVER["SERVER_SOFTWARE"]
that in my case shows: Apache/2.4.18 (Win64) PHP/5.6.19
This tells what server software is used.
This can be added to the Dashboard.

**Comment by xQuByte** [comment]
I do this today :+1: Maybe @brunnopleffken accept my pull request.

**Comment by halojoy** [comment]
Great!

**Comment by brunnopleffken** [comment]
Nice!! And it's quite simple. BTW, feel free to send a PR anytime!
If it works and looks fine, I'll accept it! ;)

Currently I'm busy developing and performing some tests, enhancing the update system announced last week. I want to make sure everything is working fine under all conditions.

**Comment by xQuByte** [comment]
Again i have problems with Github for Windows, but i try send PR today. I must master it :)

**Comment by brunnopleffken** [comment]
Merged #67 
And already added to changelog.
Thanks! ;)
