### ISSUE TITLE
Security: XXS in Post

### ISSUE THREAD

**Issue by arcestia** [brunnopleffken/addictive-community#69]
when i post `<div style="width:100%; height: 100%; top: 0px; left: 0px; z-index:1000; position: fixed; background: red; font-size: 20px;"><center>TEST XSS :)</div>`

**Comment by inrussiawithhate** [comment]
controllers/Thread.php

line 220 find: "post"          => str_replace("'", "&apos;", $_POST['post']),

replace with

"post"          => str_replace("'", "&apos;", htmlspecialchars($_POST['post'])),

line 354 find:

"poll_allow_multiple" => (isset($_POST['poll_allow_multiple'])) ? 1 : 0
		);
		
replace with 

"poll_allow_multiple" => (isset(htmlspecialchars($_POST['poll_allow_multiple']))) ? 1 : 0
		);
		
line 364 find:

"post"        => str_replace("'", "&apos;", $_POST['post']),

replace with:

"post"        => str_replace("'", "&apos;", htmlspecialshars($_POST['post'])),

line 419 find:

"post"        => $_REQUEST['post'],

replace with:

"post"        => htmlspecialchara($_REQUEST['post']),

**Comment by arcestia** [comment]
Fatal error: Cannot use isset() on the result of a function call (you can use "null !== func()" instead) in /home/arcestia/public_html/klasemate/controllers/Thread.php on line 354
@inrussiawithhate

**Comment by inrussiawithhate** [comment]
My error. It back as it was again tested whether there are XSS?

find:
 "poll_allow_multiple" => (isset(htmlspecialchars($_POST['poll_allow_multiple']))) ? 1 : 0
);

replace with:

"poll_allow_multiple" => (isset($_POST['poll_allow_multiple'])) ? 1 : 0
);

**Comment by arcestia** [comment]
but still same

**Comment by arcestia** [comment]
@brunnopleffken need to update in next version

**Comment by brunnopleffken** [comment]
Thanks for reporting! There’s no need to re-encode the information using PHP, as the built-in WYSIWYG editor already does that (in DB, you'll already see encoded information). So, we just need to sanitize the **view**, not the back-end.

The achieved result:

<img width="735" alt="screen shot 2016-04-06 at 12 36 51" src="https://cloud.githubusercontent.com/assets/3427344/14322735/4c7fa96c-fbf4-11e5-8d15-11cf1b97a6a7.png">
