### ISSUE TITLE
can't edit template

### ISSUE THREAD

**Issue by zalexstudios** [brunnopleffken/addictive-community#72]
ERORR!
`Warning: require_once(sources/adm_templates_edit.php): failed to open stream: No such file or directory in /home/m/metaldetru/bb/public_html/admin/main.php on line 77

Fatal error: require_once(): Failed opening required 'sources/adm_templates_edit.php' (include_path='.:/usr/share/php5:/usr/share/php') in /home/m/metaldetru/bb/public_html/admin/main.php on line 77`

**Comment by zalexstudios** [comment]
I'm will be translate into Russian

**Comment by zalexstudios** [comment]
New mistake!
Try to translate.

`Warning: stripslashes() expects parameter 1 to be string, array given in /home/m/metaldetru/bb/public_html/kernel/Http.php on line 33

Warning: Invalid argument supplied for foreach() in /home/m/metaldetru/bb/public_html/admin/process.php on line 280
Error!

An error occoured on the following query: INSERT INTO c_logs (member_id, time, act, ip_address) VALUES ('1', '1459785077', 'Edited language file 'login' from 'en_US'', '92.126.55.101');


You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'login' from 'en_US'', '92.126.55.101')' at line 2

`

**Comment by brunnopleffken** [comment]
Wow, single quotes inside "single quoted" string... Such a bad mistake!
This is quite simple to solve, I'll send a commit in a few minutes.

By the way, thanks for translating it to Russian!!! :D

**Comment by zalexstudios** [comment]
See here: http://bb.metaldetector38.ru
it's testing :-)

**Comment by brunnopleffken** [comment]
A tip: inside the `languages` folder, duplicate the en_US and rename it to ru_RU (the ICU locale standard for native Russian language). Inside it, just edit all the PHP files... There's just an array `key => 'value'`, you'll get it in a minute! Don't forget to also edit the JSON file, so the language package file will be credited to you, with your name in it! Much better and faster than editing via Admin CP... ;)

BTW, I'm glad Unicode is working properly with cyrillic character set, HAHAHA
Unicode support in MySQL + PHP is a little clumsy...


_PS: I'm fixing the SQL syntax error right now._

**Comment by zalexstudios** [comment]
need reinstall? Or update?

**Comment by brunnopleffken** [comment]
There's no need to reinstall. Just update the files!

**Comment by zalexstudios** [comment]
Test it! Nice work!
