### ISSUE TITLE
Report abuse

### ISSUE THREAD

**Issue by zalexstudios** [brunnopleffken/addictive-community#75]
Show bug:
Warning: require(templates/default/ajax.phtml): failed to open stream: No such file or directory in /home/m/metaldetru/bb/public_html/index.php on line 182

Warning: require(templates/default/ajax.phtml): failed to open stream: No such file or directory in /home/m/metaldetru/bb/public_html/index.php on line 182

Fatal error: require(): Failed opening required 'templates/default/ajax.phtml' (include_path='.:/usr/share/php5:/usr/share/php') in /home/m/metaldetru/bb/public_html/index.php on line 182

**Comment by brunnopleffken** [comment]
My bad! When defining page templates, strings are case-sensitive.
This seems to be solved now! ;)

Thanks!
