### ISSUE TITLE
Delete post

### ISSUE THREAD

**Issue by zalexstudios** [brunnopleffken/addictive-community#76]
If I Administrator. How can I delete a post or topic

**Comment by brunnopleffken** [comment]
Right above "Related Threads", you'll see the Admin/Mod options! ;)

<img width="349" alt="screen shot 2016-04-06 at 00 17 44" src="https://cloud.githubusercontent.com/assets/3427344/14304854/08f6ed02-fb8d-11e5-9500-7615b301d483.png">
