### ISSUE TITLE
Notice Undefined variable in installer.php

### ISSUE THREAD

**Issue by halojoy** [brunnopleffken/addictive-community#78]
Undefined variable: description in \install\installer.php on line 332

**Comment by halojoy** [comment]
I got this Notice 2 timeswhen I tested the installer.
For some reason $description does not get a value. Don't know why ...
Maybe add an initial value in the beginning of file will solve this.

**Comment by halojoy** [comment]
I have a fix for this.
In the installer.php
-----------
323		default:
324			$status = 0;
325			$description = '';
326	}
------------
This solves the Notice. Gives $description an empty value.

**Comment by brunnopleffken** [comment]
Done!! This seems to be solved, then.

**Comment by halojoy** [comment]
yes.
