### ISSUE TITLE
Addictive Community is still rather small

### ISSUE THREAD

**Issue by halojoy** [brunnopleffken/addictive-community#81]
I have made a list of forum software. It shows the size of the app.
Compared to the big forums AC is rather small.
My own QuickerBB is of course very small ....
`
vBulletin			        31.2 MB
Vanilla				14.1	
phpBB				12.2
myBB				 7.6
Simple Machines Forum	 7.0

Phorum				 4.0
Addictive Community	 3.2
Luna				 3.0
Fudforum			         2.9
featherBB			         2.7
esoTalk				 1.9
punBB				 1.8
fluxBB				 1.4
miniBB				 0.583
QuickerBB			 0.069

Drupal				48.8 MB
Joomla				30.6
Wordpress			21.2
`

**Comment by arcestia** [comment]
your QuickerBB is less than 100kb ?

**Comment by halojoy** [comment]
Yes, with 4 language files it is only 69 kB

**Comment by zalexstudios** [comment]
The main thing is not the size but the content and form of the forum!

**Comment by halojoy** [comment]
This is true, zalexstudios.
I just think it is interesting how big different applications are.
Addictive Community is in the midlle regarding size.

**Comment by brunnopleffken** [comment]
Nice research @halojoy! But in general that's my idea, a full-featured forum and being light-weight while not *appearing* light-weight... I see two main reasons for this to happen:

- Custom framework built from scratch for AC, not a full-featured framework with unnecessary things (for example, phpBB uses Symfony) and, of course, follow the DRY ("don't repeat yourself") principle.
- Less images as possible! I use of CSS for gradients, fonts and vectorized icons (not bitmap images). Visually, there's a lot of inspiration from Swiss design, and this helps to keep things light and clean.

And BTW, most of it's size is from embedded third-party components, like TinyMCE, CodeMirror and Font Awesome...

**Comment by zalexstudios** [comment]
The main thing that was the most convenient forum! As for the users and for the Administration. And how many megabytes it takes does not matter to me!

**Comment by zalexstudios** [comment]
Brunnopleffken! Do not listen to anybody! Just do the trick! Your forum I really like! I plan to make the transfer to Chinese!

**Comment by brunnopleffken** [comment]
I may be the guy who had the idea and codes this, but actually, as an open-source forum, AC belongs to the developer's community. There were a lot of new ideas (some of them still not implemented, like #58) and bug fixes, including those from you @halojoy and @zalexstudios, what makes Addictive Community even better! I'm here to hear and I'm thankful to it.

I'm still programming the update module (#64), this will make AC as a viable option for production environment (as you know, this is still a Beta version, although in an advanced stage). My idea is a visually clean and light-weight forum software that can be highly competitive against other open-source forums.

**Comment by halojoy** [comment]
You are doing a great job. I have been surprised many times how easy you fix things.
But of course you know your sofftware better than anyone.
I think AC will become a little bigger. But still not as big as the really big forums.
