### ISSUE TITLE
Attachments settings

### ISSUE THREAD

**Issue by halojoy** [brunnopleffken/addictive-community#83]
Most boards have settings, restrictions for attachments.
- extension check, what files can be uploded
- size check, how big files are allowed
- number of attached files per post

I can not see AC have any restrictions yet.
I have uploaded one 2.4 MB image .. was alright.

It is not too difficult to add some settings for this.
And some error messages when people post too much.

**Comment by brunnopleffken** [comment]
Actually AC do validates file extensions (as seen in _kernel/Upload.php_, lines 40 and 69), but the dangerous file extensions are written directly into code and are not customizable. But it doesn't validates file size...

About file size validation, indeed it's very easy to implement this! I'll add a new setting and add this validation to Upload.php.

**Comment by halojoy** [comment]
Good to know dangerous extentions are tested.
By default I see forums use like 500kB size.
But for normal images this is too small. 
At least 2MB as default I think. Maybe 3MB.

**Comment by brunnopleffken** [comment]
It's done! I set 2 MB as default. I believe it's enough for most of files and images but, of course, this can be changed in Thread/Post settings in Admin CP.

**Comment by halojoy** [comment]
Good. I will have a look.
I believe it works.

**Comment by brunnopleffken** [comment]
Yes, reinstall is needed due to it.
