### ISSUE TITLE
Swedish translation to ^0.9.0 features

### ISSUE THREAD

**Issue by brunnopleffken** [brunnopleffken/addictive-community#84]
This is assigned to our Swedish friend, @halojoy.

Version 0.9.0 presented us a new feature to schedule thread opening and locking time.
Well, an image worth a thousand words:

<img width="653" alt="screen shot 2016-04-13 at 03 33 20" src="https://cloud.githubusercontent.com/assets/3427344/14484725/b446625a-0128-11e6-91d2-724c861f1abf.png">

The base dictionary file is **languages/en_US/thread.php**.

_This reminds me I need to do the same with pt-BR. Everything is OK with Russian language._

**Comment by halojoy** [comment]
I am sorry I have missed this you have assigned to me.
But now I have translated the swedish lang-file.
It is those lines with AUTO-open and close.
I have the result in a php-file: thread.php

Where should I commit it?
I have Tortoise Subversion, so I can easily commit to your files.
Which means I have every version of Addicted Community in my computer!

**Comment by brunnopleffken** [comment]
@halojoy Just fork the project in the current state (halojoy/addictive-community), modify the files and open a pull request targeting the _development_ branch. ;)

Unfortunately there's no way to commit directly to this repository without a PR.
