### ISSUE TITLE
SQL Injection Vulnerability & XSS

### ISSUE THREAD

**Issue by Anti067** [brunnopleffken/addictive-community#98]
Hello
deal with web and server security, so I decided to test addictive community
, it turns out that there are vulnerabilities affecting security.

1// SQL Injection Vulnerability
![vulnerable](https://cloud.githubusercontent.com/assets/20012204/16170338/1621a9cc-3558-11e6-888a-ea7eca6b5483.jpg)

URL: /thread/5?p=%40%40fotSu 
Parameter: [p]

![vuln2](https://cloud.githubusercontent.com/assets/20012204/16170346/5f467d62-3558-11e6-9397-1495fa5496d2.jpg)

When there is no set ID parameter, the interpreter returns empty result, and therefore error - and it should be fine.

URL: /room

2// XSS Vulnerability

URL: /members?order=post'%22()%26%25<acx><script>prompt(999465)</script>

**Comment by brunnopleffken** [comment]
The framework already deals with numeric-only parameters, sanitizing all other characters. I'll double-check this to ensure the data security, I must pass this "numeric-only" parameter manually using _true_, like `Http::Request("var_name", true)`.

About the optional parameters (like 'p', which indicates the page number of a given thread), good point! I'll see if I can implement this kind of default value to avoid blank variables.
